Repository Alfresco/alfresco-mobile-workspace-ios, pull requests merged in 2021-04, with the labels that each got.

#313 Removed CI trigger for develop branch
  azure-pipelines.yml
Labels: PR: reviewed-approved

#314 Added NSCameraUsageDescription key to InfoPlist
  ContentApp/Supporting Files/Info.plist
Labels: PR: reviewed-approved

#315 Added dual and triple camera support when capturing images
  ContentApp/Modules/CameraKit/Components/CameraSlider.swift
  ContentApp/Modules/CameraKit/Models/CameraFeatures.swift
  ContentApp/Modules/CameraKit/Screens/CameraViewController.swift
Labels: PR: reviewed-approved

#316 Mobileapps 740
  ContentApp/Modules/CameraKit/Components/CameraSlider.swift
  ContentApp/Modules/CameraKit/Models/CameraFeatures.swift
  ContentApp/Modules/CameraKit/Screens/CameraViewController.swift
  ContentApp/Modules/CameraKit/Sessions/PhotoCaptureSession.swift
  ContentApp/PresentationLayer/Camera/Sub-Coordinators/CameraScreenCoordinator.swift
Labels: PR: reviewed-approved

#318 Mobileapps 741
  ContentApp/Modules/CameraKit/Screens/Base.lproj/Camera.storyboard
  ContentApp/Modules/CameraKit/Screens/FullScreenCapturedAssetViewController.swift
Labels: PR: reviewed-approved

#320 Added range slider component
  ContentApp.xcodeproj/project.pbxproj
  ContentApp/Modules/CameraKit/Components/RangeSlider.swift
Labels: PR: reviewed-approved

#322 Added range slider component
  ContentApp.xcodeproj/project.pbxproj
  ContentApp/Modules/CameraKit/Components/RangeSlider.swift
Labels: PR: reviewed-approved

#319 Mobileapps 740
  ContentApp.xcodeproj/project.pbxproj
  ContentApp/BusinessLayer/Localization/LocalizationConstants.swift
  ContentApp/BusinessLayer/Localization/en.lproj/Localizable.strings
  ContentApp/Modules/CameraKit/Components/CameraSlider.swift
  ContentApp/Modules/CameraKit/Components/FlashMenu.swift
  ContentApp/Modules/CameraKit/Components/RangeSlider.swift
  ContentApp/Modules/CameraKit/Components/SessionPreview.swift
  ContentApp/Modules/CameraKit/Extensions/CameraConfigurationLayout.swift
  ContentApp/Modules/CameraKit/Extensions/UIDeviceOrientation+VideoOrientation.swift
  ContentApp/Modules/CameraKit/Models/CameraFeatures.swift
  ContentApp/Modules/CameraKit/Screens/Base.lproj/Camera.storyboard
  ContentApp/Modules/CameraKit/Screens/CameraViewController+Layout.swift
  ContentApp/Modules/CameraKit/Screens/CameraViewController.swift
  ContentApp/Modules/CameraKit/Screens/FullScreenCapturedAssetViewController.swift
  ContentApp/Modules/CameraKit/Screens/PreviewViewController.swift
  ContentApp/Modules/CameraKit/Sessions/CaptureSession.swift
  ContentApp/Modules/CameraKit/Sessions/PhotoCaptureSession.swift
  ContentApp/PresentationLayer/Action Menu/Screens/ActionMenuViewController.swift
  ContentApp/PresentationLayer/Camera/Sub-Coordinators/CameraScreenCoordinator.swift
  ContentApp/PresentationLayer/Extensions/UIColor+Hex.swift
  ContentApp/PresentationLayer/Services/ThemingService/Themes/DarkTheme.swift
  ContentApp/PresentationLayer/Services/ThemingService/Themes/DefaultTheme.swift
  ContentApp/PresentationLayer/Services/ThemingService/Themes/PresentationTheme.swift
  ContentApp/Supporting Files/Resources/Assets.xcassets/Camera /ic-camera-flash-auto.imageset/Contents.json
  ContentApp/Supporting Files/Resources/Assets.xcassets/Camera /ic-camera-flash-auto.imageset/fill.pdf
  ContentApp/Supporting Files/Resources/Assets.xcassets/Camera /ic-camera-flash-off.imageset/outline.pdf
  ContentApp/Supporting Files/Resources/Assets.xcassets/Camera /ic-camera-focus-marks.imageset/Contents.json
  ContentApp/Supporting Files/Resources/Assets.xcassets/Camera /ic-camera-focus-marks.imageset/base.pdf
  ContentApp/Supporting Files/Resources/Assets.xcassets/Camera /ic-camera-switch.imageset/Contents.json
  ContentApp/Supporting Files/Resources/Assets.xcassets/Camera /ic-camera-switch.imageset/Union.pdf
  ContentApp/Supporting Files/Resources/Assets.xcassets/Camera /ic-camera-switch.imageset/outline.pdf
Labels: PR: unreviewed

#323 Mobileapps 741
  ContentApp/BusinessLayer/Localization/en.lproj/Localizable.strings
  ContentApp/Modules/CameraKit/Screens/Base.lproj/Camera.storyboard
  ContentApp/Modules/CameraKit/Screens/FullScreenCapturedAssetViewController.swift
  ContentApp/Modules/CameraKit/Screens/PreviewViewController.swift
Labels: PR: reviewed-approved

#324 Added camera button component
  ContentApp.xcodeproj/project.pbxproj
  ContentApp/Modules/CameraKit/Components/CameraButton.swift
Labels: PR: partially-approved

#325 Mobileapps 740
  ContentApp/BusinessLayer/Constants/KeyConstants.swift
  ContentApp/DataAccessLayer/DiskService.swift
  ContentApp/Modules/CameraKit/Components/CameraButton.swift
  ContentApp/Modules/CameraKit/Components/CameraSlider.swift
  ContentApp/Modules/CameraKit/Components/FlashMenu.swift
  ContentApp/Modules/CameraKit/Components/RangeSlider.swift
  ContentApp/Modules/CameraKit/Components/SessionPreview.swift
  ContentApp/Modules/CameraKit/Extensions/CameraConfigurationLayout.swift
  ContentApp/Modules/CameraKit/Models/CapturedAsset.swift
  ContentApp/Modules/CameraKit/Screens/Base.lproj/Camera.storyboard
  ContentApp/Modules/CameraKit/Screens/CameraViewController.swift
  ContentApp/Modules/CameraKit/Sessions/CaptureSession.swift
  ContentApp/Modules/CameraKit/Sessions/PhotoCaptureSession.swift
  ContentApp/Modules/CameraKit/ViewModels/CameraViewModel.swift
  ContentApp/PresentationLayer/Camera/Sub-Coordinators/CameraScreenCoordinator.swift
  ContentApp/PresentationLayer/Services/ThemingService/Themes/DarkTheme.swift
  ContentApp/PresentationLayer/Services/ThemingService/Themes/DefaultTheme.swift
  ContentApp/PresentationLayer/Services/ThemingService/Themes/PresentationTheme.swift
Labels: PR: reviewed-approved

#327 Changed camera button type to custom
  ContentApp/Modules/CameraKit/Components/CameraButton.swift
Labels: PR: reviewed-approved

#328 Fixed shutter button color in camera viewporrt
  ContentApp/Modules/CameraKit/Extensions/CameraConfigurationLayout.swift
  ContentApp/Modules/CameraKit/Screens/CameraViewController.swift
  ContentApp/PresentationLayer/Camera/Sub-Coordinators/CameraScreenCoordinator.swift
  ContentApp/PresentationLayer/Services/ThemingService/Themes/DarkTheme.swift
  ContentApp/PresentationLayer/Services/ThemingService/Themes/DefaultTheme.swift
  ContentApp/PresentationLayer/Services/ThemingService/Themes/PresentationTheme.swift
Labels: PR: reviewed-approved

#329 Bumped minimun deployment target to iOS 14 to align with AppStore rules
  ContentApp.xcodeproj/project.pbxproj
Labels: PR: reviewed-approved

#330 Mobileapps 740
  ContentApp/Modules/CameraKit/Components/FlashMenu.swift
  ContentApp/Modules/CameraKit/Components/RangeSlider.swift
  ContentApp/Modules/CameraKit/Components/SessionPreview.swift
  ContentApp/Modules/CameraKit/Screens/Base.lproj/Camera.storyboard
  ContentApp/Modules/CameraKit/Screens/CameraViewController.swift
Labels: PR: reviewed-approved

#331 Removed unused localisation languages
  ContentApp.xcodeproj/project.pbxproj
Labels: PR: reviewed-approved

#332 Fixed warnings caused by deprecation in iOS 13.0
  ContentApp/BusinessLayer/File Preview/FilePreview.swift
  ContentApp/BusinessLayer/Settings/ViewModels/SettingsViewModel.swift
  ContentApp/Modules/CameraKit/Components/RangeSlider.swift
  ContentApp/Modules/CameraKit/Models/CameraFeatures.swift
  ContentApp/PresentationLayer/Extensions/UIColor+Hex.swift
  ContentApp/PresentationLayer/Extensions/UIView/UIView+LayerTransformations.swift
  ContentApp/PresentationLayer/Extensions/UIViewController/UIViewController+Hierarchy.swift
  ContentApp/PresentationLayer/Services/ThemingService/ThemingService.swift
  ContentAppUITests/ContentAppUITests.swift
Labels: PR: reviewed-approved

#333 Fixed camera viewport height for iPad Air 4
  ContentApp/Modules/CameraKit/Screens/CameraViewController+Layout.swift
Labels: PR: reviewed-approved

#334 Mobileapps 741
  ContentApp/Modules/CameraKit/Extensions/UIDeviceOrientation+VideoOrientation.swift
  ContentApp/Modules/CameraKit/Screens/Base.lproj/Camera.storyboard
  ContentApp/Modules/CameraKit/Screens/CameraViewController.swift
Labels: PR: reviewed-approved

#335 Refactored captured media files handling on the disk
  ContentApp.xcodeproj/project.pbxproj
  ContentApp/BusinessLayer/Constants/KeyConstants.swift
  ContentApp/BusinessLayer/Extensions/Data+Hash.swift
  ContentApp/BusinessLayer/Extensions/String+Encoding.swift
  ContentApp/BusinessLayer/Extensions/String+Paths.swift
  ContentApp/DataAccessLayer/DiskService.swift
  ContentApp/Modules/CameraKit/Protocol/CameraKitCaptureDelegate.swift
  ContentApp/Modules/CameraKit/ViewModels/PreviewViewModel.swift
  ContentApp/PresentationLayer/Camera/Sub-Coordinators/CameraScreenCoordinator.swift
Labels: PR: unreviewed

#336 Camera viewport now defaults to the main camera of the device
  ContentApp.xcodeproj/project.pbxproj
  ContentApp/Modules/CameraKit/Components/RangeSlider.swift
  ContentApp/Modules/CameraKit/Components/SessionPreview.swift
  ContentApp/Modules/CameraKit/Extensions/AVCaptureDevice+Zoom.swift
  ContentApp/Modules/CameraKit/Extensions/Collection+SafeRange.swift
  ContentApp/Modules/CameraKit/Models/CapturedAsset.swift
  ContentApp/Modules/CameraKit/Screens/CameraViewController.swift
  ContentApp/Modules/CameraKit/Sessions/PhotoCaptureSession.swift
Labels: PR: unreviewed

#337 Corrected expected layout orientation for face up/down use cases
  ContentApp/Modules/CameraKit/Extensions/UIDeviceOrientation+VideoOrientation.swift
Labels: PR: unreviewed

#338 Replaced protocol conformance from class to AnyObject given the deprecation status
  ContentApp/BusinessLayer/Action Menu/ViewModels/ActionMenuViewModel.swift
  ContentApp/BusinessLayer/Action Menu/ViewModels/CreateNodeViewModel.swift
  ContentApp/BusinessLayer/Action Menu/ViewModels/NodeActionsViewModel.swift
  ContentApp/BusinessLayer/Authentication/ViewModels/AimsViewModel.swift
  ContentApp/BusinessLayer/Authentication/ViewModels/BasicAuthViewModel.swift
  ContentApp/BusinessLayer/Authentication/ViewModels/ConnectViewModel.swift
  ContentApp/BusinessLayer/Choose Dialog/ViewModels/MultipleChoiceViewModelProtocol.swift
  ContentApp/BusinessLayer/EventDelivery/EventObservable.swift
  ContentApp/BusinessLayer/File Preview/ViewModels/FilePreviewViewModel.swift
  ContentApp/BusinessLayer/Lists/ViewModels/Protocols/ListComponentDataSourceProtocol.swift
  ContentApp/BusinessLayer/Search/ViewModels/ResultsViewModel.swift
  ContentApp/BusinessLayer/Search/ViewModels/SearchViewModelProtocol.swift
  ContentApp/BusinessLayer/Services/SyncService.swift
  ContentApp/BusinessLayer/Session/AIMSAccount.swift
  ContentApp/BusinessLayer/Session/AccountProtocol.swift
  ContentApp/BusinessLayer/Settings/ViewModels/SettingsViewModel.swift
  ContentApp/BusinessLayer/Sync/SyncOperationFactory.swift
  ContentApp/Modules/CameraKit/Components/CameraSlider.swift
  ContentApp/Modules/CameraKit/Components/FlashMenu.swift
  ContentApp/Modules/CameraKit/Components/RangeSlider.swift
  ContentApp/Modules/CameraKit/Protocol/CameraKitCaptureDelegate.swift
  ContentApp/Modules/CameraKit/Sessions/CaptureSession.swift
  ContentApp/Modules/CameraKit/ViewModels/CameraViewModel.swift
  ContentApp/PresentationLayer/Authentication/Screens/SplashViewController.swift
  ContentApp/PresentationLayer/Authentication/Sub-Coordinators/AdvancedSettingsScreenCoordinator.swift
  ContentApp/PresentationLayer/Authentication/Sub-Coordinators/AimsScreenCoordinator.swift
  ContentApp/PresentationLayer/Authentication/Sub-Coordinators/BasicAuthScreenCoordinator.swift
  ContentApp/PresentationLayer/Authentication/Sub-Coordinators/ConnectScreenCoordinator.swift
  ContentApp/PresentationLayer/Authentication/Sub-Coordinators/SplashScreenCoordinator.swift
  ContentApp/PresentationLayer/Components/ListComponent/ListComponent+Delegates.swift
  ContentApp/PresentationLayer/Components/PDFRenderer/PDFRenderer.swift
  ContentApp/PresentationLayer/Components/PageFetchableCollectionView.swift
  ContentApp/PresentationLayer/Files Preview/Screens/Factory/FilePreviewProtocol.swift
  ContentApp/PresentationLayer/Files Preview/Sub-Coordinators/FilePreviewScreenCoordinator.swift
  ContentApp/PresentationLayer/List/Screens/Cells/ListElementCollectionViewCell.swift
  ContentApp/PresentationLayer/List/Screens/ResultViewController.swift
  ContentApp/PresentationLayer/List/Sub-Coordinators/BrowseScreenCoordinator.swift
  ContentApp/PresentationLayer/Settings/Screens/Cells/SettingsTableViewCellProtocol.swift
  ContentApp/PresentationLayer/Settings/Sub-Coordinators/SettingsScreenCoordinator.swift
  ContentApp/PresentationLayer/TabBar/Screens/TabBarMainViewController.swift
  ContentApp/PresentationLayer/TabBar/Sub-Coordinators/TabBarScreenCoordinator.swift
Labels: PR: unreviewed

#340 Solved compiler complaint about naming convention
  ContentApp/Modules/CameraKit/DataSources/PhotoGalleryDataSource.swift
Labels: PR: unreviewed

#341 Changed zoom slider into a brighter color for all themes
  ContentApp/Modules/CameraKit/Screens/CameraViewController.swift
Labels: PR: unreviewed

#342 Fixed photo gallery crash and video upload issues
  ContentApp/Modules/CameraKit/DataSources/PhotoGalleryDataSource.swift
  ContentApp/Modules/CameraKit/Models/CapturedAsset.swift
  ContentApp/Modules/CameraKit/Screens/PreviewViewController.swift
  ContentApp/Modules/CameraKit/ViewModels/PreviewViewModel.swift
  ContentApp/PresentationLayer/Camera/Sub-Coordinators/CameraScreenCoordinator.swift
  ContentApp/PresentationLayer/Camera/Sub-Coordinators/PhotoLibraryScreenCoordinator.swift
Labels: PR: unreviewed
