Repository Alfresco/alfresco-mobile-workspace-ios, pull requests merged in 2022-08, with the labels that each got.

#489 Mobileapps 1301
  ContentApp.xcodeproj/project.pbxproj
  ContentApp.xcodeproj/xcshareddata/xcschemes/ContentApp.xcscheme
  ContentApp/BusinessLayer/Action Menu/Models/ActionMenu.swift
  ContentApp/BusinessLayer/Analytics /AnalyticsConstants.swift
  ContentApp/BusinessLayer/Analytics /AnalyticsManager+ActionEvents.swift
  ContentApp/BusinessLayer/Constants/KeyConstants.swift
  ContentApp/BusinessLayer/Localization/LocalizationConstants.swift
  ContentApp/BusinessLayer/Localization/en.lproj/Localizable.strings
  ContentApp/BusinessLayer/Search/Models/SearchChipItem.swift
  ContentApp/BusinessLayer/Search/ViewModels/SearchViewModel.swift
  ContentApp/Modules/Advance Search/Calendar/SearchCalendarComponentViewController.swift
  ContentApp/Modules/Advance Search/Calendar/SearchCalendarComponentViewModel.swift
  ContentApp/Modules/Advance Search/List/SearchListComponentController.swift
  ContentApp/Modules/Advance Search/List/SearchListComponentViewController.swift
  ContentApp/Modules/Advance Search/List/SearchListComponentViewModel.swift
  ContentApp/Modules/Advance Search/Text/SearchTextComponentViewController.swift
  ContentApp/Modules/Advance Search/Text/SearchTextComponentViewModel.swift
  ContentApp/Modules/Advance Search/Views/Table Cells/List Item/ListItemTableViewCell.swift
  ContentApp/Modules/Advance Search/Views/Table Cells/List Item/ListItemTableViewCell.xib
  ContentApp/Modules/CameraKit/Extensions/ExtensionUIViewController.swift
  ContentApp/PresentationLayer/Components/SystemSearchViewController.swift
  ContentApp/PresentationLayer/Extensions/UIViewController/UIViewController+Settings.swift
  ContentApp/PresentationLayer/List/Screens/ResultViewController.swift
  ContentApp/PresentationLayer/Storyboard/Tasks.storyboard
  ContentApp/PresentationLayer/Tasks/Models/Task Filters/TaskChipItem.swift
  ContentApp/PresentationLayer/Tasks/Models/Task Filters/TaskFilters.swift
  ContentApp/PresentationLayer/Tasks/Models/Task Filters/task_filters.json
  ContentApp/PresentationLayer/Tasks/Models/Task Node/TaskNode.swift
  ContentApp/PresentationLayer/Tasks/Models/Task Node/TaskNodeOperations.swift
  ContentApp/PresentationLayer/Tasks/Task List/Collection Cells/List/TaskListCollectionCellViewModel.swift
  ContentApp/PresentationLayer/Tasks/Task List/Collection Cells/List/TaskListCollectionViewCell.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/TasksListViewController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/TasksListViewModel.swift
  ContentApp/PresentationLayer/Tasks/Views/Controllers/TasksListViewController.swift
  ContentApp/PresentationLayer/Tasks/Views/XIBs/Sort and Filter/TasksSortAndFilterView.swift
  ContentApp/PresentationLayer/Tasks/Views/XIBs/Sort and Filter/TasksSortAndFilterView.xib
  ContentApp/PresentationLayer/Tasks/Views/XIBs/Sort and Filter/TasksSortAndFilterViewModel.swift
  ContentApp/Supporting Files/GoogleService-Info.plist
  ContentAppTests/TestSearchListComponentViewModel.swift
  ContentAppTests/TestSearchTextComponentViewModel.swift
  Podfile.lock
Labels: PR: reviewed-approved

#490 date range filter added
  ContentApp.xcodeproj/project.pbxproj
  ContentApp/BusinessLayer/Localization/en.lproj/Localizable.strings
  ContentApp/BusinessLayer/Search/ViewModels/SearchViewModel.swift
  ContentApp/Modules/Advance Search/Calendar/SearchCalendarComponentViewModel.swift
  ContentApp/Modules/Advance Search/List/SearchListComponentController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/TaskListFilterParams.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/TasksListViewController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/TasksListViewModel.swift
  ContentApp/PresentationLayer/Tasks/Views/XIBs/Sort and Filter/TasksSortAndFilterView.swift
  ContentApp/PresentationLayer/Tasks/Views/XIBs/Sort and Filter/TasksSortAndFilterViewModel.swift
Labels: PR: reviewed-approved

#491 added check for dates
  ContentApp/Modules/Advance Search/Calendar/SearchCalendarComponentViewModel.swift
  Podfile.lock
Labels: PR: unreviewed

#493 Mobileapps 1302
  ContentApp/PresentationLayer/Storyboard/Tasks.storyboard
Labels: PR: unreviewed

#496 task attachment callback added
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Detail/TaskDetailController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Detail/TaskDetailViewController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Detail/TaskDetailViewModel.swift
  ContentApp/PresentationLayer/Tasks/Views/Table Cells/Attachment Table Cell/TaskAttachmentTableCellViewModel.swift
  ContentApp/PresentationLayer/Tasks/Views/Table Cells/Attachment Table Cell/TaskAttachmentTableViewCell.swift
  ContentApp/PresentationLayer/Tasks/Views/Table Cells/Attachment Table Cell/TaskAttachmentTableViewCell.xib
Labels: PR: unreviewed

#498 Mobileapps 1303
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Detail/TaskDetailController.swift
Labels: PR: unreviewed

#499 fixed feedback points
  ContentApp/BusinessLayer/Localization/LocalizationConstants.swift
  ContentApp/BusinessLayer/Localization/en.lproj/Localizable.strings
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Comments/TaskCommentsViewController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Comments/TaskCommentsViewModel.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Detail/TaskDetailController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Task Properties/TaskPropertiesViewModel.swift
  ContentApp/PresentationLayer/Tasks/Views/Table Cells/Task Comment/TaskCommentTableViewCell.swift
Labels: PR: unreviewed

#501 Mobileapps 1305
  ContentApp/DataAccessLayer/DiskService.swift
  ContentApp/PersistenceLayer/DataAccessors/ListNodeDataAccessor.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Detail/TaskDetailViewController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Task Properties/TaskProperties+APIs.swift
  ContentApp/Supporting Files/GoogleService-Info.plist
Labels: PR: unreviewed

#502 Mobileapps 1305
  ContentApp/BusinessLayer/File Preview/ViewModels/FilePreviewViewModel.swift
  ContentApp/DataAccessLayer/DiskService.swift
  ContentApp/PresentationLayer/Files Preview/Sub-Coordinators/FilePreviewScreenCoordinator.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Attachments/TaskAttachmentsViewController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Detail/TaskDetailViewController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Task Properties/TaskProperties+APIs.swift
  ContentApp/PresentationLayer/Tasks/Task List/Task Properties/TaskPropertiesViewModel.swift
  ContentApp/Supporting Files/GoogleService-Info.plist
Labels: PR: partially-approved

#503 Mark task as complete
  ContentApp/BusinessLayer/Localization/LocalizationConstants.swift
  ContentApp/BusinessLayer/Localization/en.lproj/Localizable.strings
  ContentApp/PresentationLayer/Storyboard/Tasks.storyboard
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Comments/TaskCommentsViewController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Detail/TaskDetailController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Detail/TaskDetailViewController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Detail/TaskDetailViewModel.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task List/TasksListViewController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Task Properties/TaskProperties+APIs.swift
  ContentApp/PresentationLayer/Tasks/Task List/Task Properties/TaskPropertiesViewModel.swift
  Podfile.lock
Labels: PR: unreviewed

#505 Fixed cancel preview issue
  ContentApp/PresentationLayer/Tasks/Task List/Task Properties/TaskProperties+APIs.swift
Labels: PR: unreviewed

#504 LOC-384 - Updated UI files for iOS ADW 1.4 app in 5 languages
  ContentApp/BusinessLayer/Localization/de.lproj/Localizable.strings
  ContentApp/BusinessLayer/Localization/es.lproj/Localizable.strings
  ContentApp/BusinessLayer/Localization/fr.lproj/Localizable.strings
  ContentApp/BusinessLayer/Localization/it.lproj/Localizable.strings
  ContentApp/BusinessLayer/Localization/nl.lproj/Localizable.strings
Labels: PR: unreviewed

#506 Mobileapps 1387
  ContentApp.xcodeproj/project.pbxproj
  ContentApp.xcodeproj/xcshareddata/xcschemes/ContentApp.xcscheme
  ContentApp/BusinessLayer/Analytics /AnalyticsConstants.swift
  ContentApp/BusinessLayer/Analytics /AnalyticsManager+ActionEvents.swift
  ContentApp/BusinessLayer/Localization/en.lproj/Localizable.strings
  ContentApp/PresentationLayer/Extensions/UILabel+NumberOfLines.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Detail/TaskDetailController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Detail/TaskDetailViewController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task List/TasksListViewController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task List/TasksListViewModel.swift
  ContentApp/PresentationLayer/Tasks/Task List/Task Properties/TaskProperties+APIs.swift
  ContentApp/PresentationLayer/Tasks/Views/Table Cells/Task Comment/TaskCommentTableViewCell.swift
  ContentApp/PresentationLayer/Tasks/Views/Table Cells/Task Comment/TaskCommentTableViewCell.xib
  Podfile
  Podfile.lock
Labels: PR: unreviewed

#507 LOC-384 - second updated to UI files for iOS ADW mobile app 1.4
  ContentApp/BusinessLayer/Localization/de.lproj/Localizable.strings
  ContentApp/BusinessLayer/Localization/es.lproj/Localizable.strings
  ContentApp/BusinessLayer/Localization/fr.lproj/Localizable.strings
  ContentApp/BusinessLayer/Localization/it.lproj/Localizable.strings
  ContentApp/BusinessLayer/Localization/nl.lproj/Localizable.strings
Labels: PR: unreviewed

#508 Hide filter chips
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task List/TasksListViewController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task List/TasksListViewModel.swift
Labels: PR: unreviewed

#509 Test cases goring
  ContentApp.xcodeproj/project.pbxproj
  ContentApp/BusinessLayer/Constants/KeyConstants.swift
  ContentApp/BusinessLayer/Localization/de.lproj/Localizable.strings
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Attachments/TaskAttachmentsViewController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Comments/TaskCommentsViewController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Detail/TaskDetailViewController.swift
  ContentApp/PresentationLayer/Tasks/Task List/Controller/Task List/TasksListViewController.swift
  ContentAppTests/Tasks/TestTaskCommentsViewModel.swift
  ContentAppTests/Tasks/TestTaskDetailViewModel.swift
  ContentAppTests/Tasks/mockComments.json
  ContentAppTests/Tasks/mockTasks.json
Labels: PR: unreviewed
